### PR TITLE
docs: include server folder npm install

### PR DESCRIPTION
**Pull request by snowfluke**

### CODE REVIEW

**Comment by Alexistoribiogit** [comment]
Hi, the code doesn't work, I have a blank page, can you fix the problem


0] 
[0] > react-template@1.0.1 start
[0] > react-scripts start
[0]
[1]
[1] > react-template@1.0.1 server
[1] > nodemon server/server.js
[1]
[1] 'nodemon' n'est pas reconnu en tant que commande interne
[1] ou externe, un programme exï¿½cutable ou un fichier de commandes.
[1] npm run server exited with code 1
[0] (node:12572) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[0] (Use `node --trace-deprecation ...` to show where the warning was created)
[0] (node:12572) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[0] Starting the development server...
[0]
[0] Compiled with warnings.
[0]
[0] Failed to parse source map from 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\format.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\format.ts'
[0]
[0] Failed to parse source map from 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\index.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\index.ts'
[0]
[0] Failed to parse source map from 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\lang\en_US.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\lang\en_US.ts'
[0]
[0] Failed to parse source map from 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\lang\zh_CN.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\lang\zh_CN.ts'
[0]
[0] Failed to parse source map from 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\realtime.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\realtime.ts'
[0]
[0] Failed to parse source map from 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\register.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\register.ts'
[0]
[0] Failed to parse source map from 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\utils\date.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\utils\date.ts'
[0]
[0] Failed to parse source map from 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\utils\dom.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\utils\dom.ts'
[0]
[0] [eslint]
[0] src\components\ChatMessage.js
[0]   Line 2:22:  'MdPersonOutline' is defined but never used  no-unused-vars
[0]
[0] Search for the keywords to learn more about each warning.
[0] To ignore, add // eslint-disable-next-line to the line before.
[0]
[0] WARNING in ./node_modules/timeago.js/esm/format.js
[0] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[0] Failed to parse source map from 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\format.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\format.ts'
[0]
[0] WARNING in ./node_modules/timeago.js/esm/index.js
[0] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[0] Failed to parse source map from 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\index.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\index.ts'
[0]
[0] WARNING in ./node_modules/timeago.js/esm/lang/en_US.js
[0] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[0] Failed to parse source map from 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\lang\en_US.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\lang\en_US.ts'
[0]
[0] WARNING in ./node_modules/timeago.js/esm/lang/zh_CN.js
[0] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[0] Failed to parse source map from 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\lang\zh_CN.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\lang\zh_CN.ts'
[0]
[0] WARNING in ./node_modules/timeago.js/esm/realtime.js
[0] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[0] Failed to parse source map from 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\realtime.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\realtime.ts'
[0]
[0] WARNING in ./node_modules/timeago.js/esm/register.js
[0] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[0] Failed to parse source map from 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\register.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\register.ts'
[0]
[0] WARNING in ./node_modules/timeago.js/esm/utils/date.js
[0] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[0] Failed to parse source map from 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\utils\date.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\utils\date.ts'
[0]
[0] WARNING in ./node_modules/timeago.js/esm/utils/dom.js
[0] Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
[0] Failed to parse source map from 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\utils\dom.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\jerem\Desktop\chatgpt-clone-main\node_modules\timeago.js\src\utils\dom.ts'
[0]
[0] WARNING in [eslint]
[0] src\components\ChatMessage.js
[0]   Line 2:22:  'MdPersonOutline' is defined but never used  no-unused-vars
[0]
[0] webpack compiled with 9 warnings

**Comment by snowfluke** [comment]
@Alexistoribiogit 

```bash
cd server
npm install
```

**Comment by Alexistoribiogit** [comment]
Hi, the code doesn't work, I have a blank page, can you fix the problem


PS G:\Nouveau dossier\chatgpt-clone-main> npm run dev
   
> react-template@1.0.1 dev
> concurrently "npm start" "npm run server"

[1] 
[1] > react-template@1.0.1 server
[1] > nodemon server/server.js
[1]
[0]
[0] > react-template@1.0.1 start
[0] > react-scripts start
[0]
[1] [nodemon] 2.0.20
[1] [nodemon] to restart at any time, enter `rs`
[1] [nodemon] watching path(s): *.*
[1] [nodemon] watching extensions: js,mjs,json
[1] [nodemon] starting `node server/server.js`
[1] Server listening on port 3001
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[1] [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
[1]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)

**Comment by Alexistoribiogit** [comment]
help me please

**Pull request merged**
